### PR TITLE
Create test_diagnostic.py

### PR DESCRIPTION
**Pull request by AOstenfeld**
# Pull Request
### Description
Adding tests for the FieldDiagnostic class in diagnostics.py

This pull request addresses #96 
- [ ] init
- [ ] check_step
- [ ] do_diagnostic
- [ ] inspect_resource
- [ ] print_diagnose
- [ ] initialize
- [ ] csv diagnose
- [ ] finalize

- [ ] make sure you are pulling from a dev branch on your fork
- [ ] check for code linting

### CODE REVIEW

**Comment by AOstenfeld** [comment]
This is supposed to be a draft but I can't seem to change it.

**Comment by padamson** [comment]
Weird...I can't make it draft either.

**Comment by padamson** [comment]
I made it draft. There's something fishy going on with the UI. It didn't seem like it wanted to let me make it draft, but it did after waiting a few seconds.

**Comment by AOstenfeld** [comment]
I'm closing this and creating a new PR with the same contests because I messed something up with git. Whoops

**Pull request closed without merging**
