### PR TITLE
Create test_remove_files.py

### PR DESCRIPTION
**Pull request by kphlips**
# Pull Request
## Description
Creates a test file that runs last and removes unnecessary folders.

This pull request addresses #136 
Fixes #

## Checklist
The following items have been checked for this PR:

- [x] Conforms to PEP8 style standards (check with `pylint`, `flake8`, or similar)
- [x] Code is documented with docstrings, or docstrings have been updated as appropriate
- [ ] New unit test/integration test have been added to check new code
- [x] All existing tests still pass

### CODE REVIEW

**Comment by arichar6** [comment]
Is this the standard method for cleaning up after pytests? If so can you add a link that shows an example?

Also, you say above that this should run last... how do you know it will be last?

**Comment by kphlips** [comment]
@arichar6 [Here](https://github.com/pytest-dev/pytest/issues/3051) is the example that I found about how to run something after test completion. I moved the method to `conftest.py` and deleted the old test that ran last due to its name coming last alphabetically.

**Comment by arichar6** [comment]
This looks better.

However, it seems like pytest has tools which can be used to [create temporary directories as part of a fixture](https://docs.pytest.org/en/latest/tmpdir.html). Can you investigate, and see how hard it would be to use this part of the pytest API, rather than hard-coding paths for the temporary files?

**Comment by kphlips** [comment]
I don't think this would be an easier approach, given that, for example, `default_output` is generated inside of `core.py` and therefore would require significant changes in order to utilize the pytest temporary directory. Knowing this, I think that having the file deletion method inside of `conftest.py` is the easiest way to move forward and possibly only add another `shutil.rmtree()` statement should another temporary file need to be deleted after testing.

**Comment by kphlips** [comment]
On a different note, does the `conftest.py` within the tests folder need to be updated as well?

**Comment by arichar6** [comment]
> I don't think this would be an easier approach, given that, for example, `default_output` is generated inside of `core.py` and therefore would require significant changes in order to utilize the pytest temporary directory. 

First, just because on approach is easier does not mean that it's better.

Second, there should be a way to run the app within a pytest temporary directory, so that the `default_output` folder gets created inside of the temp folder. You should be able to do this without changing anything in `core.py`.

> On a different note, does the `conftest.py` within the tests folder need to be updated as well?

If you are going to modify the `conftest.py` files, then you should be working in the one with scope closest to what you need. So yes, you should modify the one in the `tests` folder, instead of changing the one in the root.

**Comment by kphlips** [comment]
@arichar6 It should just take some changing of file path in `fixtures` (where temporary files are created) and in the tests (where they are accessed), by adding a fixture `tmp_path` imported from pytest.

**Comment by kphlips** [comment]
> @arichar6 It should just take some changing of file path in `fixtures` (where temporary files are created) and in the tests (where they are accessed), by adding a fixture `tmp_path` imported from pytest. I'll see if that does the trick.

It turns out pytest does not automatically delete the directory after testing...
I've implemented the temporary `tmp_path` for `test_bos.py`, and also added a method to delete that, next I will do the same for `test_core.py`

**Comment by kphlips** [comment]
Now that I look at `test_core.py`, given that the pytest directories must be deleted on their own, wouldn't it make more sense to delete the `default_output` folder after the two tests that use it are finished? The folder is only used to check that the names created are correct, so it could be removed right after `test_default_diagnostic_filename_is_generated_if_no_name_specified` and `test_default_diagnostic_filename_increments_for_multiple_diagnostics`.

**Comment by arichar6** [comment]
> It turns out pytest does not automatically delete the directory after testing...

This is not entirely true. From [this page](https://docs.pytest.org/en/stable/tmpdir.html):

> Temporary directories are by default created as sub-directories of the system temporary directory. The base name will be pytest-NUM where NUM will be incremented with each test run. Moreover, entries older than 3 temporary directories will be removed.

So, two things. First, since the temporary directory is created in the system tmp dir, it can be deleted by the system (e.g. during reboot). Second, once the tests are run more than three times, the oldest temporary directory is deleted. I just tested this using the example linked at the top of the page I linked above.

**Comment by kphlips** [comment]
@arichar6 Sorry this has been such a mess, I think it's now in a state that I'm happy with. All of the temporary files are created in or eventually moved to the `temp_path` folder.

**Comment by arichar6** [comment]
> @arichar6 Sorry this has been such a mess, I think it's now in a state that I'm happy with. All of the temporary files are created in or eventually moved to the `temp_path` folder.

Don't worry about it! Sometimes you have to make a mess to get things to work. 😆 

I'll take a look at this, to see how it's working now.

**Comment by arichar6** [comment]
I just made a PR to your `136-Remove-files` branch. It shows how to use the `tmp_path` fixture... you didn't have it quite correct. I implemented this for the block-on-spring example. You can follow this pattern for the other tests.

**Comment by arichar6** [comment]
Here's a link to the PR: https://github.com/kphlips/turbopy/pull/1/files

**Pull request merged**
