### PR TITLE
add xarray to environment.yml

### PR DESCRIPTION
**Pull request by padamson**
Satisfies #37

### CODE REVIEW

**Comment by arichar6** [comment]
Do we want to add an additional dependency? I really like `xarray` so far, and would love to use it. I'm a bit hesitant to add more requirements to the core framework. Part of being a lightweight framework is that it has minimal dependencies. I've even wondered if I should remove the `qtoml` dependency.

Thoughts?

**Comment by padamson** [comment]
I thought we agreed environment.yml was going to be for a development environment, not for turbopy dependencies. We need xarray for the particle_in_field integration test that I'm putting in.

**Comment by GarethTMorgan** [comment]
@padamson I took a look at the xarray website and saw that the big draw is that you can apply and utilize labels on an array. how are you planning on using this feature in the particle-in-field integration test?

**Comment by padamson** [comment]
It’s already used in tests/fixtures/particle_in_field/particle_in_field.py. We need to think through exactly if/how we want to use example apps for testing, but one approach is just to store “good” output in tests/fixtures/particle_in_field/ and and compare the output from the test to the stored data.  There is even a way to compare output from plots to “good” images of plots. 

 

--

Paul Adamson, PhD

Naval Research Laboratory, Code 6770.1

4555 Overlook Ave. SW

Washington, DC 20375-5320

(o) 202-404-4284

(c) 202-570-8424

**Comment by GarethTMorgan** [comment]
Cool! Thank you

**Comment by arichar6** [comment]
I didn't realize you were using xarray in the tests. And good point about this being a dev environment.

**Pull request merged**
