### PR TITLE
Create documentation for turboPy

### PR DESCRIPTION
**Pull request by arichar6**
Starting to work on the documentation for turboPy, as described in #1.

### CODE REVIEW

**Comment by arichar6** [comment]
So, I'm still learning how to use autodoc and sphinx to create the html documentation. I'm also thinking about how much documentation should go into the rst files in the docs folder, vs how much should go in the docstrings.

I'm open to suggestions. I kind of like how [the numpy.org documentation](https://numpy.org/doc/stable/) looks like there is some high-level content (which presumably is in something like static rst files?) and also has automatically generated lower-level content such as the [Numpy API Reference](https://numpy.org/doc/stable/reference/index.html). I think something like this would work well for turboPy.

**Comment by padamson** [comment]
I kind of like the numpy.org approach, too, but the further away the documentation is from the source the higher risk of having outdated documentation. (Admins/reviewers should review docstrings in any source as it is committed, but we may forget or fail to check relevant docs/*.rst.) Of course even docstrings at the lowest level can be outdated or wrong.

One thought is to treat the documentation in docs/*.rst as "integrated documentation" that describe examples of code use and how multiple objects and methods can be used together. The docstrings at the module level give an overview of the objects in that module. Object/method docstrings are the lowest level.

**Comment by arichar6** [comment]
I agree with your assessment of the risk of having the documentation "too far" from the source. I think that for now I will try and keep the docs/*.rst files for organizing the automatically generated documentation, with the goal of eventually adding some "integrated documentation" as you describe.

**Comment by arichar6** [comment]
I found [a blog post](https://brendanhasz.github.io/2019/01/05/sphinx.html) where the author describes how to get started with Sphinx and ReadTheDocs. It gives a nice, high-level overview. 

I'm putting the link here for reference, for my future self and any others who will be helping with this documentation project.

**Comment by arichar6** [comment]
I've created a (hidden) version of the documentation at ReadTheDocs that is automatically generated from this branch. Whenever commits are pushed to this branch, the online docs will get updated:
https://turbopy.readthedocs.io/en/dev-documentation

**Comment by arichar6** [comment]
I didn't realize that GitHub has a "draft PR" feature. This basically enforces the WIP conventions. I think we can move to using draft PRs. I suppose we can continue to use the [WIP] naming convention, but I think the "draft" feature is easier.

**Comment by arichar6** [comment]
I think that we need to close this PR, and then delete the associated branch.

**Pull request merged**
