### PR TITLE
[WIP] Add contributing md

### PR DESCRIPTION
**Pull request by littlewatkins**
This first pass is an outline for the contribution guide.

Things to be added:
- More on issue description (templates, etc)
- On making pull requests
- Adding links to doc pages

### CODE REVIEW

**Comment by arichar6** [comment]
🤦 

I just saw the [WIP] label... were you not done? I can try to revert...

**Comment by padamson** [comment]
LOL…Can you add to the CONTRIBUTING.md to use the draft feature for PRs if you don’t want them merged? It’s too easy to miss [WIP]. The draft feature blocks merging.

 

--

Paul Adamson, PhD

Naval Research Laboratory, Code 6770.1

4555 Overlook Ave. SW

Washington, DC 20375-5320

(o) 202-404-4284

(c) 202-570-8424

**Comment by arichar6** [comment]
Hmm... I think I'd rather not try to revert. That would require a new PR, and seems unnecessarily complicated. Can you just open a new PR if you have more changes?

Thanks, and again... sorry about that.

**Comment by arichar6** [comment]
Totally! We should definitely use the draft feature.

**Comment by GarethTMorgan** [comment]
this PR addresses #4

**Comment by littlewatkins** [comment]
Haha no worries @arichar6. 
And a draft feature? I didn't know that was a thing. I'll make some more changes to the contributing and make another pull request haha

**Comment by GarethTMorgan** [comment]
@littlewatkins let me know if you would like assistance with contributing.md. I'd be happy to help

**Comment by littlewatkins** [comment]
@GarethTMorgan I would love some help. I'm adding some stuff about pull requests rn, but if you could add some things about templates, that'd be great. Also add anything to other sections (both already existing or not)

**Comment by GarethTMorgan** [comment]
Would you like to just make some issue and PR templates as well?

**Comment by littlewatkins** [comment]
You can if you want! I created an issue for the templates.

**Pull request merged**
