### PR TITLE
Another 04 contribution

### PR DESCRIPTION
**Pull request by littlewatkins**
I added Pull Request info. More info needed on issue templates and things I haven't thought about.

### CODE REVIEW

**Comment by GarethTMorgan** [comment]
is it possible for me to add my file to this PR? or do I just have to create another request?

**Comment by arichar6** [comment]
You can make a PR to the `littlewatkins/turbopy` branch. I think.

**Comment by GarethTMorgan** [comment]
oooh, thats smart.

**Comment by arichar6** [comment]
Not sure if that means you have to for his repo though. That seems like too much bother...

**Comment by GarethTMorgan** [comment]
is it just me or is the issues section in there twice? GitHub's changes presentation solution makes my head hurt haha.

**Comment by littlewatkins** [comment]
Somehow the Issue section got copied and pasted. I removed it

**Comment by padamson** [comment]
We can resolve the conflicts for this particular PR fairly easily, but for future reference (and larger PRs), please try to update main (or dev-documentation as appropriate) and starting a new branch for each PR. I think you started from your existing `04-contribution-md` branch instead of fetching upstream, merging upstream/main, and starting a new branch.

**Comment by littlewatkins** [comment]
Duly noted as that's exactly what I did lol.

**Comment by padamson** [comment]
I speak from experience, too. Lol

**Comment by GarethTMorgan** [comment]
@littlewatkins is this still a draft PR?

**Comment by littlewatkins** [comment]
@GarethTMorgan I hadn't really added anything to it. But it could be merged and then others can add to it

**Comment by GarethTMorgan** [comment]
it says it has merge conflicts, I'm 90% sure that means an admin needs to resolve the conflicts before it can be merged. But I agree that this should probably get merged and open the file up for other people to add to it.

**Comment by arichar6** [comment]
> ... an admin needs to resolve the conflicts before it can be merged.

I think that you can pull from `main` into your branch. If there are conflicts, they will show up. You can resolve them in your branch however you think best, and then push a new commit with the conflicts resolved.

Let me know if that doesn't work.

**Comment by littlewatkins** [comment]
I say merge and then adjust from there

**Pull request merged**
