### PR TITLE
Partial documentation for computetools.py

### PR DESCRIPTION
**Pull request by OwenGrannis**
# Pull Request
### Description
Add docstrings to computetools.py, including all four classes within it.

This pull request addresses #54

- [x] make sure you are pulling from a dev branch on your fork
- [x] check for code linting

### CODE REVIEW

**Comment by OwenGrannis** [comment]
In the PoissonSolver solve() method, what's would the argument `sources` look like (i.e. datatype and typical structure)?
I'm trying to figure out how the method works so I can document it properly, but I can't tell what `sources` is supposed to be.

**Comment by padamson** [comment]
@OwenGrannis we are going to close this PR and delete the dev-documentation branch here. We are switching policy to branch off main to develop documentation. Please resubmit the PR to pull into main.

**Comment by arichar6** [comment]
@padamson: I was able to change this to point to `main`.
@OwenGrannis: How close are you being done with this PR? We discussed this morning that we should probably take the approach of doing "small" PRs that can be completed in ~day, rather than working on one huge PR.

**Comment by OwenGrannis** [comment]
There were some things that aren't done, but on the whole, they can be separate tasks (like documentation for the FiniteDifference class), and all of those have been noted with TODO. I think it's fine to merge it in now.

**Pull request merged**
